# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 01:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPSecrets',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='otp_secret', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('secret', models.CharField(db_index=True, max_length=16)),
            ],
        ),
    ]
