# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpsecrets',
            name='issuer_name',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
