name: Deploy

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest twine
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Replace the version
        run: "sed -i -e \"s/\\[VERSION\\]/${{ github.ref_name }}/\" setup.py"
      - name: Create the package
        run: python setup.py sdist
      - name: Deploy
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
